### ISSUE TITLE
1.6.0 pkg

### ISSUE THREAD

**Issue by baajiru** [sendyhalim/Yomu#15]
can you upload the pkg installer for 1.6.0? Thanks

**Comment by sendyhalim** [comment]
Hi @frncsc1 thanks for the issue, I've fixed the travis build+deploy problem yesterday. It's working now https://github.com/sendyhalim/Yomu/releases you can download the latest release there. :beers:

**Comment by baajiru** [comment]
hi @sendyhalim, new installer still installs 1.5.0 version and does not work properly (all blank). Thank you again!

**Comment by sendyhalim** [comment]
@frncsc1  I forgot to bump the version in the xcode build settings, however I tried to install the one in the release, it works properly, maybe you should add the manga to read? (You can click the button at the top left corner). I'll republish the version to match the latest xcode build though. 

<img width="882" alt="screen shot 2018-07-25 at 20 02 22" src="https://user-images.githubusercontent.com/3948217/43202422-b2069d58-9045-11e8-91e0-ddcb95eadd34.png">
<img width="882" alt="screen shot 2018-07-25 at 20 02 19" src="https://user-images.githubusercontent.com/3948217/43202423-b23e59c8-9045-11e8-863e-c4097771df33.png">

**Comment by baajiru** [comment]
You're right it works! Thanks, it's a great application

**Comment by sendyhalim** [comment]
Glad to hear that! I'm gonna republish 1.6.0 so that the installed version number is updated (won't interfere with any fixes in you current installation), it's just for consistency.
