### ISSUE TITLE
Zoom webtoon - limit to 150%

### ISSUE THREAD

**Issue by gorgoserio** [sendyhalim/Yomu#3]
Hi, i've been facing issue when reading webtoon on Yomu, since the zoom only goes up to 150% and is not enough for some chap, i'd suggest that if there's webtoon in tag genre of the manga (or with a simple switch) it start a 'webtoon-mode' in which the chap's img are 80/100% of the width.

**Comment by sendyhalim** [comment]
Hi @gordonwes, 

actually, I'm planning to make zoom percentage editable by providing zoom input field, so you can zoom out or zoom in without limit (min 10%, max screen width)

**Comment by sendyhalim** [comment]
I just released version [1.2.4](https://github.com/sendyhalim/Yomu/releases/tag/1.2.4) which supports flexible zoom (you can set your own zoom level). Please feel free to re-open the issue if it's not working well :beers:

**Comment by gorgoserio** [comment]
Nice! I'll try it right now :thumbsup:
