### ISSUE TITLE
The window does not appear again after closing the latter

### ISSUE THREAD

**Issue by gorgoserio** [sendyhalim/Yomu#5]
Hi, as wrote in the subject after you close the window from the red button, remains only the icon in the dock, and if you click it nothing happens.
In addition to the subject, i noticed that the window doesn't resize to fit the screen on double click.

N.B: macOS 10.12.1 (16B2555) Retina, 13-inch, Late 2013

**Comment by sendyhalim** [comment]
Yep I noticed that too, it seems that there's a bug with the new transparent title bar. For a workaround, you should be able to quit the app by pressing `⌘ + Q`. For the window size that doesn't fit to the screen, could you please post a screenshot of it?

**Comment by sendyhalim** [comment]
Ok I found the issue, I just fixed it c1edaa2ec0e02bd41151760fc788c61a2dd226b0, I will publish another release (bump version) tomorrow 👍

**Comment by sendyhalim** [comment]
Ok version [1.2.5](https://github.com/sendyhalim/Yomu/releases/tag/1.2.5) should have it fixed :beers:, you can give it a try
