### ISSUE TITLE
Feature request - next chap

### ISSUE THREAD

**Issue by gorgoserio** [sendyhalim/Yomu#6]
Hi, it would be nice if you introduce the option to go directly to the next chapter without exit from the latter!
Keep the good work! :thumbsup:

**Comment by sendyhalim** [comment]
+1, I've been thinking about this too, I'll see what I can do this weekend

**Comment by sendyhalim** [comment]
@gordonwes 1.3.0 just released https://github.com/sendyhalim/yomu/releases/tag/1.3.0, added a feature to navigate between chapters (previous and next chapter) on chapter page screen :tada:

Let me know if there's something that I miss 🍻
